- name: Instalar el paquete de Python3-venv (si no está instalado)
  ansible.builtin.apt:
    name: python3-venv
    state: present
    update_cache: yes
  become: true

- name: Crear un entorno virtual de Python
  ansible.builtin.command:
    cmd: python3 -m venv /home/ikerlan/ansible-venv
    creates: /home/ikerlan/ansible-venv/bin/activate

- name: Instalar pip y setuptools para Python 3
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-setuptools
    state: present
    update_cache: yes
  become: true

- name: Instalar packaging en el entorno virtual
  ansible.builtin.command:
    cmd: /home/ikerlan/ansible-venv/bin/pip install packaging
  become: true

#- name: Instalar packaging en el entorno virtual
#  ansible.builtin.pip:
#    name: packaging
#    virtualenv: /home/ikerlan/ansible-venv
#    state: present
#  become: true

- name: Instalar pip en el entorno virtual
  ansible.builtin.pip:
    name: pip
    virtualenv: /home/ikerlan/ansible-venv
    state: latest

- name: Instalar paquetes en el entorno virtual
  ansible.builtin.pip:
    name:
      - kubernetes
      - ansible
    virtualenv: /home/ikerlan/ansible-venv
    state: latest

- name: Activar entorno virtual y asegurarse de que pyyaml esté instalado
  ansible.builtin.pip:
    name: pyyaml
    virtualenv: /home/ikerlan/ansible-venv
    state: present
