- name: Ensure /etc/rancher/k3s/k3s.yaml is readable by kubectl
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'  # Permisos de lectura para todos
    owner: root
    group: root

- name: Fetch kubectl config file
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/kube-config
    flat: true   # override the default behavior of appending hostname/path/to/file to the destination
