master:
  hosts:
    pc1:
      ansible_host: 172.16.60.21
      ansible_user: ikerlan
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

workers:
  hosts:
    pc3:
      ansible_host: 172.16.60.23
      ansible_user: ikerlan
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_mv3
    pc4:
      ansible_host: 172.16.60.24
      ansible_user: ikerlan
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_mv4

cluster-master:
  hosts:
    kube1:
      ansible_host: 172.16.60.22
      ansible_user: ikerlan
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_mv2

cluster-workers:
  hosts:
    kube2:
      ansible_host: 172.16.60.25
      ansible_user: ikerlan
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_mv5

non-cluster-members:
  children:
    master:
    workers:


cluster-members:
  children:
    cluster-master:
    cluster-workers:


all:
  children:
    master:
    workers:
    cluster-master:
    cluster-workers:
