---

- name: Add Prometheus Helm chart repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Prometheus Helm chart
  kubernetes.core.helm:
    release_name: my-prometheus
    chart_ref: prometheus-community/prometheus
    chart_version: 22.7.0
    state: present # present / absent: use this to remove installation
    release_namespace: monitoring
    create_namespace: true
    values:
      server:
        service:
          type: NodePort
          nodePort: 31000
        retention: "30d"

- name: Registrar Prometheus en Consul server
  uri:
    url: "http://172.16.60.21:8500/v1/agent/service/register"
    method: PUT
    body: |
      {
        "ID": "prometheus-cluster",
        "Name": "prometheus-cluster",
        "Address": "{{ ansible_default_ipv4.address }}",
        "Port": 31000,
        "Tags": ["federated"],
        "Check": {
          "HTTP": "http://{{ ansible_default_ipv4.address }}:31000/-/healthy",
          "Interval": "30s"
        }
      }
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 200


       #serverFiles:
        #  prometheus.yml: |
        #    scrape_configs:
      #    - job_name: 'kubernetes-nodes-cadvisor'
      #         scheme: https
      #         scrape_interval: 10s
      #         tls_config:
      #           ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #           insecure_skip_verify: true
      #         bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #         kubernetes_sd_configs:
      #           - role: node
      #         relabel_configs:
      #           - action: labelmap
      #             regex: __meta_kubernetes_node_label_(.+)
      #           - target_label: __address__
      #             replacement: kubernetes.default.svc:443
      #           - source_labels: [__meta_kubernetes_node_name]
      #             regex: (.+)
      #             target_label: __metrics_path__
      #             replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      #         metric_relabel_configs:
      #           - source_labels: [__name__]
      #             regex: (container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total|machine_cpu_cores|machine_memory_bytes)
      #             action: keep

      #       - job_name: 'kubernetes-service-endpoints'
      #         honor_labels: true
      #         scrape_interval: 10s
      #         kubernetes_sd_configs:
      #           - role: endpoints
      #         relabel_configs:
      #           - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      #             action: keep
      #             regex: true
      #           - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
      #             action: drop
      #             regex: true
      #           - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      #             action: replace
      #             target_label: __scheme__
      #             regex: (https?)
      #           - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      #             action: replace
      #             target_label: __metrics_path__
      #             regex: (.+)
      #           - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      #             action: replace
      #             target_label: __address__
      #             regex: (.+?)(?::\d+)?;(\d+)
      #             replacement: $1:$2
      #           - action: labelmap
      #             regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
      #             replacement: __param_$1
      #           - action: labelmap
      #             regex: __meta_kubernetes_service_label_(.+)
      #           - source_labels: [__meta_kubernetes_namespace]
      #             action: replace
      #             target_label: namespace
      #           - source_labels: [__meta_kubernetes_service_name]
      #             action: replace
      #             target_label: service
      #           - source_labels: [__meta_kubernetes_pod_node_name]
      #             action: replace
      #             target_label: node
      #         metric_relabel_configs:
      #           - source_labels: [__name__]
      #             regex: (kube_node_info|node_disk_io_now|kube_namespace_created|kube_pod_container_info)
      #             action: keep

      #       - job_name: 'prometheus-pushgateway'
      #         honor_labels: true
      #         kubernetes_sd_configs:
      #           - role: service
      #         relabel_configs:
      #           - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
      #             action: keep
      #             regex: pushgateway
