#dispositivos fuera del cluster
- name: Checkear docker
  hosts: non-cluster-members
  roles:
    - check-docker

- name: Configurar el servidor de monitorizacion
  hosts: master
  vars:
    consul_role: "server"
  roles:
    - config-consul
    - install-consul
    - install-prometheus


- name: Instalar los Exporters necesarios
  hosts: workers
  vars:
    consul_role: "agent"
  roles:
    - config-consul
    - install-consul
    - install-node_exporter

#dispositivos dentro del cluster
- name: Instalar Helm
  hosts: cluster-members
  roles:
    - install-helm

- name: Configurar Master
  hosts: cluster-master
  become: true
  roles:
#    - create-virtual-env
    - config-master

- name: Configurar Nodos
  hosts: cluster-workers
  become: true
  roles:
    - config-nodes

- name: Configurar Master y Desplegar Monitorizacion
  hosts: cluster-master
#  vars:
#    ansible_python_interpreter: /home/ikerlan/ansible-venv/bin/python
  roles:
    - define-storage-class
#    - install-consul
    - install-prometheus-kubernetes #con prometheus ya se instala el node exporter
