global:
  datacenter: "cluster"

server:
  enabled: false  # Deshabilita el servidor de Consul

client:
  enabled: true   # Solo instala el agente
  join:
    - "172.16.60.21:8500"  # Se conecta al Consul Server externo
  retry_join:
    - "172.16.60.21:8500"

connectInject:
  enabled: false  # Desactiva la inyección de Connect

ui:
  enabled: false  # Desactiva la UI

#services:
#  prometheus:
#    tags:
#      - "federated"
#    port: 31000  # Puerto en el que Prometheus escucha
#    check:
#      http: "http://{{ ansible_default_ipv4.address }}:31000/-/healthy"  # Endpoint de salud de Prometheus.
#      interval: "10s"
