- name: Check if Node Exporter is installed
  become: true
  ansible.builtin.command:
    cmd: "helm list --namespace monitoring -q"
  register: helm_list_result
  failed_when: false

- name: Uninstall Node Exporter if it exists
  become: true
  ansible.builtin.command:
    cmd: "helm uninstall node-exporter --namespace monitoring"
  when: "'node-exporter' in helm_list_result.stdout"

- name: Check if Prometheus Helm repository is already added
  become: true
  ansible.builtin.command:
    cmd: "helm repo list -q"
  register: helm_repo_list_result
  failed_when: false

- name: Add Prometheus Helm repository if not already present
  become: true
  ansible.builtin.command:
    cmd: "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts"
  when: "'prometheus-community' not in helm_repo_list_result.stdout"

- name: Update Helm repositories
  become: true
  ansible.builtin.command:
    cmd: "helm repo update"

- name: Install Node Exporter as DaemonSet
  become: true
  ansible.builtin.command:
    cmd: "helm install node-exporter prometheus-community/prometheus-node-exporter --namespace monitoring --set daemonset.enabled=true"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
